/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffe0cd",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-bright": "#fef7ff",
        "surface-variant": "#e8dfee",
        "on-surface-variant": "#4a4455",
        "surface-container-high": "#ede5f4",
        "outline": "#7b7487",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-primary-fixed": "#25005a",
        "on-background": "#1d1a24",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary": "#8127cf",
        "tertiary-fixed-dim": "#ffb784",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f3ebfa",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-container": "#ede0ff",
        "on-tertiary-fixed-variant": "#713700",
        "inverse-surface": "#332f39",
        "surface": "#fef7ff",
        "tertiary": "#7d3d00",
        "surface-container-low": "#f9f1ff",
        "primary-container": "#7c3aed",
        "on-surface": "#1d1a24",
        "inverse-primary": "#d2bbff",
        "surface-tint": "#732ee4",
        "tertiary-fixed": "#ffdcc6",
        "secondary-container": "#9c48ea",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#a15100",
        "error-container": "#ffdad6",
        "primary-fixed": "#eaddff",
        "primary": "#630ed4",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e8dfee",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#301400",
        "outline-variant": "#ccc3d8",
        "surface-dim": "#dfd7e6",
        "inverse-on-surface": "#f6eefc",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "background": "#fef7ff",
        "secondary-fixed": "#f0dbff",
        "on-tertiary": "#ffffff"
      },
      spacing: {
        "gutter": "16px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "column-list": "320px",
        "column-chat": "auto",
        "padding-card": "20px",
        "column-nav": "80px"
      },
      fontFamily: {
        "body-main": ["Be Vietnam Pro", "sans-serif"],
        "h2-sidebar": ["Be Vietnam Pro", "sans-serif"],
        "h1-display": ["Be Vietnam Pro", "sans-serif"],
        "caption": ["Be Vietnam Pro", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-bold": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "body-main": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "h2-sidebar": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "h1-display": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-bold": ["15px", { lineHeight: "22px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
